#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Copy settings files.
# Skips if the destination file already exists.
# @param $1 file name
copy_settings_file()
{
	local source="https://raw.githubusercontent.com/segovia94/drupal-local-settings/master/${1}"
	local dest="${SITEDIR_PATH}/${1}"

	if [[ ! -f $dest ]]; then
		echo-green "Copying ${dest}..."
		wget -O $dest $source
	else
		echo-yellow "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

composer_install ()
{
	cd "$PROJECT_ROOT"
	echo-green "Installing dependencies..."
	composer install
}

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	copy_settings_file "services.local.yml"
	copy_settings_file "settings.local.php"
	copy_settings_file "settings.php"
}

# Fix file/folder permissions
fix_permissions ()
{
	echo-green "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
time -p composer_install
fix_permissions
init_settings

echo -e "${green-bg}DONE! ${NC}${green} Completed all initialization steps.${NC}"
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
